apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tromsfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-hmsreg-instance-gateway_tromsfylke_no
      fintlabs.no/org-id: tromsfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "tromsfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "tromsfylke.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/tromsfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/tromsfylke-no/api/hmsreg/instances/sak"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/tromsfylke-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/tromsfylke-no/actuator/prometheus"
    target:
      kind: Application
      name: fint-flyt-hmsreg-instance-gateway

