apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-hmsreg-instance-gateway_bfk_no
      fintlabs.no/org-id: bfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "bfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
      - op: add
        path: "/spec/url/basePath"
        value: "/beta/bfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/bfk-no/api/hmsreg/instances/sak"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/bfk-no/actuator/health"
    target:
      kind: Application
      name: fint-flyt-hmsreg-instance-gateway

